### ISSUE TITLE
Existential operators not working correctly

### ISSUE THREAD

**Issue by mfrye-intuit** [SimonDegraeve/cjsxify#5]
First this is a cool module. Our team has been using it for a bit.

I found this today, which could cause some problems. It seems the coffeescript transformer you're using doesn't compile this correctly.

```
if test?
  // do this
```
compiles to
```
if (test != null) {
  // do this
}
```
which should instead be
```
if (typeof test === "undefined" || test === null) {
  // do this
}
```

**Comment by namuol** [comment]
Last I knew, `// this` is not valid CoffeeScript...

Also, each transformation should be effectively the same; I've seen versions of CoffeeScript generate the simpler `!= null` existential test.

**Comment by mfrye-intuit** [comment]
My apologies ```// this ``` should be ``` # this comment```, but it isn't involved with the issues I'm seeing. 

It looks like it's using coffee-react-transform 0.2.0, which is quite old now. That could be the problem. I'll check it out.

**Comment by SimonDegraeve** [comment]
Done, updated dependencies and published to npm. Sorry for the delay.
